### ISSUE TITLE
Instructions for use?

### ISSUE THREAD

**Issue by rbarna1** [mastertinner/docker-compose-buildpack#1]
Hi there.  I was wondering today if I could use Docker Compose to push my CF images, and lo and behold someone on the internet has already tried it. :)

Does this work, and if so how does one use it? I don't see any code mapping the manifest yaml to compose yaml or vice versa, so not sure what the purpose of this build back is when running on Garden CF.

Thanks!

**Comment by cloudlena** [comment]
Thanks for the inquiry, @rbarna1. The buildpack was an experiment I conducted earlier but unfortunately, I couldn't get it to run because CF, by default, doesn't give elevated permissions to the buildpack during staging. Since Docker requires elevated permissions to be installed, it's impossible to install it in the container using a buildpack. I'm still hoping that this will be changed in the future but currently, as far as I can tell, this buildpack doesn't work. Do you see any possibilities to install Docker during staging?

**Comment by cloudlena** [comment]
Closed due to being stale
